/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SRC_MODULES_VICTRON_PB_H_INCLUDED
#define PB_SRC_MODULES_VICTRON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _VictronField {
    char key[33];
    char value[65];
} VictronField;

typedef struct _VictronData {
    pb_size_t fields_count;
    VictronField fields[32];
} VictronData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define VictronField_init_default                {"", ""}
#define VictronData_init_default                 {0, {VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default, VictronField_init_default}}
#define VictronField_init_zero                   {"", ""}
#define VictronData_init_zero                    {0, {VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero, VictronField_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define VictronField_key_tag                     1
#define VictronField_value_tag                   2
#define VictronData_fields_tag                   1

/* Struct field encoding specification for nanopb */
#define VictronField_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define VictronField_CALLBACK NULL
#define VictronField_DEFAULT NULL

#define VictronData_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  fields,            1)
#define VictronData_CALLBACK NULL
#define VictronData_DEFAULT NULL
#define VictronData_fields_MSGTYPE VictronField

extern const pb_msgdesc_t VictronField_msg;
extern const pb_msgdesc_t VictronData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define VictronField_fields &VictronField_msg
#define VictronData_fields &VictronData_msg

/* Maximum encoded size of messages (where known) */
#define SRC_MODULES_VICTRON_PB_H_MAX_SIZE        VictronData_size
#define VictronData_size                         3264
#define VictronField_size                        100

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
